# Generated by Django 2.2 on 2021-09-11 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='实验室名')),
                ('description', models.TextField(blank=True, verbose_name='实验室描述')),
            ],
            options={
                'verbose_name': '实验室',
                'verbose_name_plural': '实验室',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13, unique=True, verbose_name='药品编号')),
                ('name', models.CharField(max_length=200, verbose_name='药品名')),
                ('detail', models.TextField(blank=True, max_length=2000, verbose_name='药品信息')),
                ('nowtotal', models.IntegerField(default=0, verbose_name='药品剩余量')),
                ('usedtotal', models.IntegerField(default=0, verbose_name='药品用量')),
                ('riskfactor', models.IntegerField(default=0, verbose_name='风险因子')),
            ],
            options={
                'verbose_name': '药品列表',
                'verbose_name_plural': '药品列表',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickyName', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('cate', models.BooleanField(default=False, verbose_name='类别')),
                ('faculty', models.CharField(blank=True, default='undefine', max_length=20, verbose_name='系别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineUsedNum', models.PositiveIntegerField(default=0, verbose_name='药品使用量')),
                ('boDate', models.DateTimeField(auto_now_add=True, verbose_name='借用时间')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Lab', verbose_name='借用地点')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Medicine', verbose_name='借用药品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.CommonUser', verbose_name='借用人')),
            ],
            options={
                'verbose_name': '借用记录',
                'verbose_name_plural': '借用记录',
            },
        ),
    ]
