# Generated by Django 2.2 on 2022-02-28 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_no', models.CharField(max_length=13, unique=True, verbose_name='仪器编号')),
                ('ins_name', models.CharField(max_length=200, verbose_name='仪器名称')),
                ('ins_detail', models.TextField(blank=True, max_length=2000, verbose_name='仪器信息')),
                ('ins_nowtotal', models.IntegerField(default=0, verbose_name='仪器剩余数')),
                ('ins_bototal', models.IntegerField(default=0, verbose_name='仪器借用数')),
            ],
            options={
                'verbose_name': '仪器列表',
                'verbose_name_plural': '仪器列表',
                'ordering': ('ins_no',),
            },
        ),
        migrations.AlterModelOptions(
            name='borrow',
            options={'verbose_name': '借用药品记录', 'verbose_name_plural': '借用药品记录'},
        ),
        migrations.AlterModelOptions(
            name='commonuser',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterField(
            model_name='borrow',
            name='medicineUsedNum',
            field=models.PositiveIntegerField(default=0, verbose_name='药品使用量(/g)'),
        ),
        migrations.CreateModel(
            name='InsBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boNum', models.PositiveIntegerField(default=0, verbose_name='借用数量')),
                ('boDate', models.DateTimeField(auto_now_add=True, verbose_name='借用时间')),
                ('ins_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.CommonUser', verbose_name='借用人')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Instrument', verbose_name='借用仪器')),
            ],
            options={
                'verbose_name': '借用仪器记录',
                'verbose_name_plural': '借用仪器记录',
            },
        ),
    ]
