# Generated by Django 2.2 on 2022-02-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20220228_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insborrow',
            old_name='boDate',
            new_name='ins_boDate',
        ),
        migrations.RemoveField(
            model_name='insborrow',
            name='boNum',
        ),
        migrations.AddField(
            model_name='insborrow',
            name='ins_boNum',
            field=models.PositiveIntegerField(default=0, verbose_name='借用数量'),
        ),
    ]
